config/routes.rb
Rails.application.routes.draw do


  get 'ultrabooks/index'

	resources :estados do
			resources :cidades  ,dependent: :destroy
	end

	resources :cidades
	resources :lojas

	resources :vehicle_categories


  get 'adminarea/index'

  devise_for :admins
  root 'welcome#index'

	
  get 'sobre', to: 'welcome#sobre', as: :sobre
	get 'franquias', to: 'welcome#franquias', as: :franquias
	get 'contato', to: 'welcome#contato', as: :contato
end



# Metodologia de Implatanção Sistema Ultravisao



#  5W2H
# What ? - > O que ?
# Why ? -> Porque ?
# Who ? -> Quem ?
# How ? -> Como ?
# How-much ? -> $$ ?
# When ? -> Quando ?
# Where ? -> Aonde ?

#################################################


# ULTRA - 1. Fase

# Welcome page c/ telas empresa,contato,franchising...etc
##### devise 
##### preparar matriz
## Cadastro de Estados
### Cadastro de Cidades - Nested
#### Cadastro de Lojas
##### Fazer Background de Mapa
######  Pronto
######## Deploy 
#########################################################
		###### PRONTO ###### 2x dias - ps. ajustar mapa detran concorrencia etc. ? x ROI





# ULTRABOOK - 2. Fase


# News -> Aberto ao Público e No Navbar
##   "Abertas + 15 lojas no Brasil !!"
### Noticias afins...


################### Suporte ######################
# Cadastrar Marca e Modelo
# Cadastrar Veículo
# Listagem de Veiculos para suporte dar o Ok completed_at

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



   
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base

	belongs_to :estado
	has_many :lojas
	
	def to_param
		"#{id}-#{name}"
	end



end

app/models/estado.rb
class Estado < ActiveRecord::Base

	has_many :cidades


	def to_param
		"#{id}-#{name}"
	end


end

app/models/loja.rb
class Loja < ActiveRecord::Base


	belongs_to :cidade


		def to_param
		"#{id}-#{name}"
	end
	
end

app/models/matriz.rb
class Matriz < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle_category.rb
class VehicleCategory < ActiveRecord::Base
end

app/controllers/adminarea_controller.rb
class AdminareaController < ApplicationController

	before_action :authenticate_admin! 
  def index
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



   protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
  end


end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController

	before_action :find_cidade, only: [:show, :destroy] 
	

	def index
		@cidade = Cidade.all
		@lojas = Loja.all

	end

	def show
		@lojas = Loja.all
	end

	def new
		@cidade = Cidade.new
	end

	def create
		@cidade = Cidade.new(cidade_params)
		if @cidade.save
			redirect_to @cidade
		else
			render 'new' 
		end
	end

	def destroy
		@cidade = Cidade.find(params[:id])
    if @cidade.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end





	private

	def find_cidade
		@cidade = Cidade.find(params[:id])
	end

	def cidade_params
		params.require(:cidade).permit(:name, :estado_id, :loja_id)
	end



end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController

	before_action :find_estado, only: [:show, :edit, :update, :destroy]

#
#  Nao esquecer de ligar.
##############################################################
	before_action :authenticate_admin! , except: [:index, :show]

	def index
		@estados = Estado.all.order("name ASC")
  #  @cidades = Cidade.all
	end

	def show
      @estado = Estado.find(params[:id])
      @cidades = @estado.cidades.order("name ASC")
	end

  def edit
  end

  def new
  	@estado = Estado.new
  end

  def create
  	@estado = Estado.new(estado_params)
  	if @estado.save
  		redirect_to @estado ,notice: "Cadastrado com Sucesso"
  	else
  		render 'new'
  	end
  end

  def update
    if @estado.update(estado_params)
      redirect_to @estado, notice: "Atualizado com Sucesso"
    else
      render 'edit'
    end
  end

  def destroy
    if @estado.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end




  private

  def find_estado
  	@estado = Estado.find(params[:id])

  end

  def estado_params
  	params.require(:estado).permit(:name , :cidade_id)
  end






end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController

	before_action :find_loja, only: [:show, :edit, :update, :destroy]


	def index
		@lojas = Loja.all.order("created_at DESC")

	end

	def show
	end

	def edit
	end

	def new
		@loja = Loja.new
	end

	def create
		@loja = Loja.new(loja_params)
		if @loja.save
			redirect_to @loja, notice: "Loja Cadastrada com Sucesso"
		else
			render 'new'
		end
	end

	def update
		if @loja.update(loja_params)
			redirect_to @loja, notice: "Atualizado com Sucesso"
		else
			render 'edit'
		end
	end


	def destroy
		if @loja.destroy
				redirect_to lojas_path, notice: "Loja Deletada com Sucesso"
		end
	end










	private

	def find_loja
		@loja = Loja.find(params[:id])
	end

	def loja_params
		params.require(:loja).permit(:name, :cidade_id, :endereco, :telefone, :email, :owner, :mapa)

	end







end

app/controllers/ultrabooks_controller.rb
class UltrabooksController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


  def sobre
  end

  

  def franquias
  end

  def contato
  end
end

app/helpers/adminarea_helper.rb
module AdminareaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

		def tipo(type)
		case type
		when :success then "success"
		when :error   then "warning"
		when :alert   then "warning"
		when :notice  then " "
		else "info"
		end
	end



	def full_name
			" ( " "#{current_admin.name}"  " ) "
	end



end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/matrizs_helper.rb
module MatrizsHelper
end

app/helpers/ultrabooks_helper.rb
module UltrabooksHelper
end

app/helpers/vehicle_categories_helper.rb
module VehicleCategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/adminarea/index.html.erb
<div class="container">
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Admin Area</h1>
	<h3>Bem vindo | <%= current_admin.email %></h3>
	<hr>









</div>

app/views/ultrabooks/index.html.erb
<h1>UltraBook</h1>


<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
	
		<a class="navbar-brand" href="#">Title</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
			<li class="active"><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
		</ul>
		<form class="navbar-form navbar-left" role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="#">Link</a></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="#">Action</a></li>
					<li><a href="#">Another action</a></li>
					<li><a href="#">Something else here</a></li>
					<li><a href="#">Separated link</a></li>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

	<h3>Listagem de Notícias</h3>

			<h1 align="center"><u>"Abertas + 15 lojas no Brasil"</u></h1>

app/views/welcome/contato.html.erb
<div class="container">



	
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Fale Conosco</h1>
<hr>


<h1>Entre em contato com a Ultra</h1>
</div>

<!-- 
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "70x70", alt: "Ultravisao") %> Servicos</h1>
<hr>

<div class="row">
		
				<div class="col-md-4">
					<div class="well">
						<div align="center">
									<h2>Laudo de Transferência</h2>
					  			<hr>
					  				<li class="list-group-item"><h3>Resolucao Contran 250 de 24.09.2007</h3></li>
					  			<h5> Emitimos o laudo para transferencia de propriedade do veiculo.</h5>
					  			<hr>
					  			<h3>Itens Verificados:</h3>
					  			<h5>Sao Verificados todos os itens exigidos para a transferencia de propriedade pelo padrao Denatran, entre eles: O bloco nele instalado é original e está dentro dos padrões da montadora. 
					II – com o cadastro informatizado do veículo na BIN;
					III – com o cadastro informatizado do veículo em campo próprio da Base Estadual ou no campo das "observações" do CRV/CRLV; </h5>
					  </div>
					</div>
			</div>



			<div class="col-md-4">
					<div class="well">
						<div align="center">
									<h2>Vistoria Cautelar</h2>
					  			<hr>
					  				<li class="list-group-item"><h3>Comercializando Veículos Semi-Novos</h3></li>
					  			<h5>Você que comprou um veículo semi-novo e que se preocupa com a procedência do veículo que está adquirindo.
Fazemos uma análise técnica (Vistoria) para saber se o veículo não possui adulterações.<Br> Inclusive Documentacao</h5>
					  			<hr>
					  			<h3>Itens Verificados:</h3>
					  			<h5>Numerações do motor, chassi, câmbio, vidros, etiquetas, cortes estruturais etc.</h5>
					  </div>
					</div>
			</div>

			<div class="col-md-4">
					<div class="well">
						<div align="center">
									<h2>Tratamento de Chassi</h2>
					  			<hr>
					  				<li class="list-group-item"><h3>Limpeza do Chassi</h3></li>
					  			
					  			<hr>
					  			<h5>Este produto é disponibilizado aos clientes para a recuperação de CHASSI, seja o mesmo sofrendo desgastes pelo tempo, ferrugem ou de outra natureza. Sua comercialização refere-se a aplicação de produtos autorizados, cuja garantia e cuidados em sua aplicação é exigida pela lei de segurança no trabalho.</h5>
					  			
					  </div>
					</div>
			</div>

 -->

app/views/welcome/franquias.html.erb
<div class="container">


<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Franchising</h1>
<hr>
	
	<h3>Sua loja de vistoria veicular</h3>
	<h3>Venha ser um franqueado e abra sua loja de vistoria em sua cidade.</h3>
	
</div>

app/views/welcome/index.html.erb
<div class="container">
		<h1 id="ultra" class="animated bounceInLeft">Bem vindo a Ultravisão</h1>
		<h3 class="animated bounceInDown">Franquia de vistorias veiculares</h3>
</div>

app/views/welcome/sobre.html.erb
<div class="container">



<div class="well text-center">

<%= image_tag("logoultra250CinzaEscuro.png", size: "150x150", alt: "Ultravisao") %>
<hr>
<h1>A Empresa</h1>


	<h3><strong>Visão:</strong></h3>
		<h4>Ser a rede que melhor atende e satisfaz nossos clientes, franqueados e vistoriadores o melhor serviço de vistoria veicular em nosso segmento em toda América do Sul.</h4>
<hr>
	<h3><strong>Missão:</strong></h3>
		<h4>Nossa razão de ser é comercializar serviços que promovam a tranqüilidade de nossos clientes e criar produtos que agregam valores, para que, estejamos sempre à frente das expectativas de nossos parceiros.</h4>
<hr>
	<h3><strong>Nossa Historia:</strong></h3>
		<h4>O início da operação pericial aconteceu em Capivari, interior do Estado de São Paulo . A ULTRA VISÃO PERÍCIAS E VISTORIAS foi fundada  em 2007 após a resolução 199/06, essa portaria exigia foto com numeração do motor dos  veículos que eram de difícil visualização,ou ainda , se a numeração fosse muito fraca dificultando de ser decalcada.
Diante dessa exigência começaram a surgir problemas, tais como, veículos com motor trocado, adulterado, não restando alternativa que não fosse necessário estender o serviço também para o consumidor final na compra de seu veículo, é a garantia da procedência do mesmo.
Em parceria com amigos vistoriadores e um perito do instituto criminalista, Os proprietários abriram a <%= link_to 'Empresa', adminarea_index_path %> e onde fizeram um curso de identificação de motores veiculares, aliado com Know-how no ramo automotivo a mais de 13 anos.</h4>
</fieldset>
</div>

</div>