config/routes.rb
Rails.application.routes.draw do


  get 'ultrabooks/index'

	resources :estados do
			resources :cidades  ,dependent: :destroy
	end

	resources :cidades
	resources :lojas

	resources :vehicle_categories


  get 'adminarea/index'

  devise_for :admins
  root 'welcome#index'

	
  get 'sobre', to: 'welcome#sobre', as: :sobre
	get 'franquias', to: 'welcome#franquias', as: :franquias
	get 'contato', to: 'welcome#contato', as: :contato
end



# Metodologia de Implatanção Sistema Ultravisao



#  5W2H
# What ? - > O que ?
# Why ? -> Porque ?
# Who ? -> Quem ?
# How ? -> Como ?
# How-much ? -> $$ ?
# When ? -> Quando ?
# Where ? -> Aonde ?

#################################################


# ULTRA - 1. Fase

# Welcome page c/ telas empresa,contato,franchising...etc
##### devise 
##### preparar matriz
## Cadastro de Estados
### Cadastro de Cidades - Nested
#### Cadastro de Lojas
##### Fazer Background de Mapa
######  Pronto
######## Deploy 
#########################################################
		###### PRONTO ###### 2x dias - ps. ajustar mapa detran concorrencia etc. ? x ROI





# ULTRABOOK - 2. Fase


# News -> Aberto ao Público e No Navbar
##   "Abertas + 15 lojas no Brasil !!"
### Noticias afins...


################### Suporte ######################
# Cadastrar Marca e Modelo
# Cadastrar Veículo
# Listagem de Veiculos para suporte dar o Ok completed_at

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



   
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base

	belongs_to :estado
	has_many :lojas
	
	def to_param
		"#{id}-#{name}"
	end



end

app/models/estado.rb
class Estado < ActiveRecord::Base

	has_many :cidades


	def to_param
		"#{id}-#{name}"
	end


end

app/models/loja.rb
class Loja < ActiveRecord::Base


	belongs_to :cidade


		def to_param
		"#{id}-#{name}"
	end
	
end

app/models/matriz.rb
class Matriz < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle_category.rb
class VehicleCategory < ActiveRecord::Base
end

app/controllers/adminarea_controller.rb
class AdminareaController < ApplicationController

	before_action :authenticate_admin! 
  def index
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?



   protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
  end


end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController

	before_action :find_cidade, only: [:show, :destroy] 
	

	def index
		@cidade = Cidade.all
		@lojas = Loja.all

	end

	def show
		@lojas = Loja.all
	end

	def new
		@cidade = Cidade.new
	end

	def create
		@cidade = Cidade.new(cidade_params)
		if @cidade.save
			redirect_to @cidade
		else
			render 'new' 
		end
	end

	def destroy
		@cidade = Cidade.find(params[:id])
    if @cidade.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end





	private

	def find_cidade
		@cidade = Cidade.find(params[:id])
	end

	def cidade_params
		params.require(:cidade).permit(:name, :estado_id, :loja_id)
	end



end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController

	before_action :find_estado, only: [:show, :edit, :update, :destroy]

#
#  Nao esquecer de ligar.
##############################################################
	before_action :authenticate_admin! , except: [:index, :show]

	def index
		@estados = Estado.all.order("name ASC")
  #  @cidades = Cidade.all
	end

	def show
      @estado = Estado.find(params[:id])
      @cidades = @estado.cidades.order("name ASC")
	end

  def edit
  end

  def new
  	@estado = Estado.new
  end

  def create
  	@estado = Estado.new(estado_params)
  	if @estado.save
  		redirect_to @estado ,notice: "Cadastrado com Sucesso"
  	else
  		render 'new'
  	end
  end

  def update
    if @estado.update(estado_params)
      redirect_to @estado, notice: "Atualizado com Sucesso"
    else
      render 'edit'
    end
  end

  def destroy
    if @estado.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end




  private

  def find_estado
  	@estado = Estado.find(params[:id])

  end

  def estado_params
  	params.require(:estado).permit(:name , :cidade_id)
  end






end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController

	before_action :find_loja, only: [:show, :edit, :update, :destroy]


	def index
		@lojas = Loja.all.order("created_at DESC")

	end

	def show
	end

	def edit
	end

	def new
		@loja = Loja.new
	end

	def create
		@loja = Loja.new(loja_params)
		if @loja.save
			redirect_to @loja, notice: "Loja Cadastrada com Sucesso"
		else
			render 'new'
		end
	end

	def update
		if @loja.update(loja_params)
			redirect_to @loja, notice: "Atualizado com Sucesso"
		else
			render 'edit'
		end
	end


	def destroy
		if @loja.destroy
				redirect_to lojas_path, notice: "Loja Deletada com Sucesso"
		end
	end










	private

	def find_loja
		@loja = Loja.find(params[:id])
	end

	def loja_params
		params.require(:loja).permit(:name, :cidade_id, :endereco, :telefone, :email, :owner, :mapa)

	end







end

app/controllers/ultrabooks_controller.rb
class UltrabooksController < ApplicationController
  def index
  end
end

app/controllers/vehicle_categories_controller.rb
class VehicleCategoriesController < ApplicationController

	before_action :find_vehicle_category, only: [:show, :destroy] 

	respond_to :html

	def index
		@vehicle_categories = VehicleCategory.all.order("name ASC")
	end

	def new
		@vehicle_category = VehicleCategory.new
	end

	def create
		@vehicle_category = VehicleCategory.new(vehicle_category_params)
		if @vehicle_category.save
			flash[:notice] = "Categoria criada com sucesso" 
			redirect_to @vehicle_category
		else
			flash[:error] = "Nao cadastrado"
			render 'new'
		end
	end

	def destroy
		 @vehicle_category.destroy
    respond_with(@vehicle_category)
	end


	private

	def find_vehicle_category
	 	 @vehicle_category = VehicleCategory.find(params[:id])
	end

	def vehicle_category_params
		params.require(:vehicle_category).permit(:name)
	end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


  def sobre
  end

  

  def franquias
  end

  def contato
  end
end

app/helpers/adminarea_helper.rb
module AdminareaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

		def tipo(type)
		case type
		when :success then "success"
		when :error   then "warning"
		when :alert   then "warning"
		when :notice  then " "
		else "info"
		end
	end



	def full_name
			" ( " "#{current_admin.name}"  " ) "
	end



end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/matrizs_helper.rb
module MatrizsHelper
end

app/helpers/ultrabooks_helper.rb
module UltrabooksHelper
end

app/helpers/vehicle_categories_helper.rb
module VehicleCategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cidades/_form.html.erb
<%= simple_form_for @cidade do |f| %>
		<%= f.input :name , input_html: { class: "form-control" }  %>
		<%= f.collection_select :estado_id , Estado.all, :id, :name , { prompt: "Qual Estado?" },class: "form-control"  %>
		<br>

		<%= f.button :submit, class: "btn btn-primary"  %>
	<% end %>

app/views/cidades/new.html.erb
	<h1>Cadastrar Cidade</h1>

	<%= render 'form'%>


<br>
	<%= link_to 'Voltar' , estados_path %>

app/views/cidades/show.html.erb
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> <%= @cidade.name %></h1>
<%= link_to 'Voltar', estados_path, class: "btn btn-default" %>

<hr>
	<% @cidade.lojas.each do |loja| %>
	<h3><%= link_to loja.name, loja %></h3>

	<% end %>

app/views/estados/_form.html.erb


<%= simple_form_for @estado do |f| %>
	<%= f.input :name %>
	<br>
	<%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/estados/edit.html.erb
<div class="container">

<h1>Editar Estado</h1>

<%= render 'form'%>

<%= link_to 'Voltar', estados_path %>


</div>

app/views/estados/index.html.erb

	
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Ultravisão no Brasil</h1>
<hr>

<% if admin_signed_in? %>
<%= link_to 'Cadastrar Estados', new_estado_path , class: "btn btn-primary"%>
<%= link_to 'Cadastrar Cidades', new_estado_cidade_path(:estado_id), class: "btn btn-primary" %>
<!-- 
<%= link_to 'Cadastrar Loja', new_loja_path, class: "btn btn-primary"  %>
 --><hr>
<% end %>

<% @estados.each do |estado| %>
	<h3><%= link_to estado.name, estado %></h3>
	<% if admin_signed_in? %>
		<%= link_to 'Edit', edit_estado_path(estado), class: "btn btn-sm btn-default" %>
			<%= link_to 'Delete', estado, method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-sm btn-danger"  %>
		<% end %>
<% end %>

app/views/estados/new.html.erb
<div class="container">

<h1>Cadastrar Estado</h1>

<%= render 'form'%>

<%= link_to 'Voltar', estados_path %>


</div>

app/views/estados/show.html.erb
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> <%= @estado.name %></h1>
<%= link_to 'Voltar', estados_path, class: "btn btn-default" %>

<hr>
	<% @cidades.each do |cidade| %>
		<h3><%= link_to cidade.name, cidade %></h3>

		<% if admin_signed_in? %>
			<%= link_to 'Deletar', cidade_path(cidade), method: :delete , data: { confirm: "Tem Certeza?" } , class: "btn btn-sm btn-danger" %>
		<% end %>
	<% end %>

app/views/lojas/_form.html.erb
<%= simple_form_for @loja do |f| %>
	<%= f.input :name, label: "Nome" %>
	<%= f.collection_select :cidade_id, Cidade.all, :id, :name ,{ prompt: "Cadastrar Cidade" } ,class: "form-control" %>
	<%= f.input :endereco %>
	<%= f.input :telefone %>
	<%= f.input :email %>
	<%= f.input :owner %>
	<%= f.input :mapa, input_html: { class: "form-control" }, label: "Mapa: Cadastrar Latitude e Longitude", placeholder: "-23.710250, -46.553102" %><Br>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/lojas/_map.html.erb

<!-- -22.704870, -46.769935 -->
<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
 
<script type="text/javascript">
 
// The latitude and longitude of your business / place
var position = [<%= @loja.mapa %>];
 
function showGoogleMaps() {
 
    var latLng = new google.maps.LatLng(position[0], position[1]);
 
    var mapOptions = {
        zoom: 16, // initialize zoom level - the max value is 21
        streetViewControl: false, // hide the yellow Street View pegman
        scaleControl: true, // allow users to zoom the Google Map
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: latLng
    };
 
    map = new google.maps.Map(document.getElementById('googlemaps'),
        mapOptions);
 
    // Show the default red marker at the location
    marker = new google.maps.Marker({
        position: latLng,
        map: map,
        draggable: false,
        animation: google.maps.Animation.DROP
    });
}
 
google.maps.event.addDomListener(window, 'load', showGoogleMaps);
</script>


app/views/lojas/edit.html.erb
<h1>Editar Loja</h1>
	<%= render 'form'%>
<%= link_to 'Voltar', lojas_path %>

app/views/lojas/index.html.erb

	
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Lojas Ultravisao</h1>

<% if admin_signed_in? %>
<%= link_to 'Cadastrar Loja', new_loja_path , class: "btn btn-primary" %>
<% end %>
<hr>


<% @lojas.each do |loja| %>
	<h3><%= link_to loja.name , loja %></h3>
	<% if admin_signed_in? %>
	<%= link_to 'Editar', edit_loja_path(loja) , class: "btn btn-sm btn-default" %>
	

	<%= link_to 'Deletar', loja, method: :delete, data: { confirm: "Tem Certeza?" }, class: "btn btn-sm btn-danger" %>
	

	<% end %>
<% end %>



app/views/lojas/new.html.erb
<h1>Cadastrar Loja</h1>
	<%= render 'form'%>
<%= link_to 'Voltar', lojas_path %>

app/views/lojas/show.html.erb


<div class="col-md-offset-7">
<div id="googlemaps"></div>
<div id="contactform">
<div class="text-center">
	<%= image_tag("logoultra250.png", size: "84x84", alt: "Logo") %>
	<h2><%=  @loja.name  %></h2>

		<h4>Endereco: <%= @loja.endereco %></h4>
		<h4>Telefone: <%= @loja.telefone %></h4>
		<h4>Email: <%= @loja.email %></h4>
        <p>Mapa<br>(Aperte F5 ou Atualize Pagina)</p>
       <%= link_to "reload", refresh: true %>
</div>
		<%= link_to 'Volta' , :back ,  class: "btn btn-info" %>
	</div>
		</div>


<!-- -22.704870, -46.769935 -->
<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
 
<script type="text/javascript">
 
// The latitude and longitude of your business / place
var position = [<%= @loja.mapa %>];



function showGoogleMaps() {
 
    var latLng = new google.maps.LatLng(position[0], position[1]);
 
    var mapOptions = {
        zoom: 16, // initialize zoom level - the max value is 21
        streetViewControl: false, // hide the yellow Street View pegman
        scaleControl: true, // allow users to zoom the Google Map
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: latLng
    };
 
    map = new google.maps.Map(document.getElementById('googlemaps'),
        mapOptions);
 
    // Show the default red marker at the location
    marker = new google.maps.Marker({
        position: latLng,
        map: map,
        draggable: false,
        animation: google.maps.Animation.DROP
    });
}
 
google.maps.event.addDomListener(window, 'load', showGoogleMaps);
</script>


app/views/vehicle_categories/index.html.erb
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> Relação de Marcas</h1>
<%= link_to 'Voltar', vehicle_categories_path, class: "btn btn-default" %>
<br><br>

	<%= link_to 'Cadastrar Marca', new_vehicle_category_path , class: "btn btn-primary" %>

<hr>

	<% @vehicle_categories.each do |c| %>
		<h3><%= link_to c.name, c %></h3>

		<% if admin_signed_in? %>
			<%= link_to 'Delete', c, method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-sm btn-danger" %>
		<% end %>
	<% end %>

app/views/vehicle_categories/new.html.erb
<h1>Cadastrar Marca</h1>
<%= simple_form_for @vehicle_category do |f| %>
	<%= f.input :name %>
	<br>
	<%= f.button :submit %>

<% end %>

<%= link_to 'Voltar', vehicle_categories_path %>

app/views/vehicle_categories/show.html.erb
	
<h1><%= image_tag("logoultra250CinzaEscuro.png", size: "100x100", alt: "Ultravisao") %> <%= @vehicle_category.name %></h1>


<%= link_to 'Voltar', vehicle_categories_path %>


<hr>