config/routes.rb
Rails.application.routes.draw do


  get 'ultrabooks/index'

	resources :estados do
			resources :cidades  ,dependent: :destroy
	end

	resources :cidades
	resources :lojas

	resources :vehicle_categories


  get 'adminarea/index'

  devise_for :admins
  root 'welcome#index'

	
  get 'sobre', to: 'welcome#sobre', as: :sobre
	get 'franquias', to: 'welcome#franquias', as: :franquias
	get 'contato', to: 'welcome#contato', as: :contato
end



# Metodologia de Implatanção Sistema Ultravisao



#  5W2H
# What ? - > O que ?
# Why ? -> Porque ?
# Who ? -> Quem ?
# How ? -> Como ?
# How-much ? -> $$ ?
# When ? -> Quando ?
# Where ? -> Aonde ?

#################################################


# ULTRA - 1. Fase

# Welcome page c/ telas empresa,contato,franchising...etc
##### devise 
##### preparar matriz
## Cadastro de Estados
### Cadastro de Cidades - Nested
#### Cadastro de Lojas
##### Fazer Background de Mapa
######  Pronto
######## Deploy 
#########################################################
		###### PRONTO ###### 2x dias - ps. ajustar mapa detran concorrencia etc. ? x ROI





# ULTRABOOK - 2. Fase


# News -> Aberto ao Público e No Navbar
##   "Abertas + 15 lojas no Brasil !!"
### Noticias afins...


################### Suporte ######################
# Cadastrar Marca e Modelo
# Cadastrar Veículo
# Listagem de Veiculos para suporte dar o Ok completed_at

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



   
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base

	belongs_to :estado
	has_many :lojas
	
	def to_param
		"#{id}-#{name}"
	end



end

app/models/estado.rb
class Estado < ActiveRecord::Base

	has_many :cidades


	def to_param
		"#{id}-#{name}"
	end


end

app/models/loja.rb
class Loja < ActiveRecord::Base


	belongs_to :cidade


		def to_param
		"#{id}-#{name}"
	end
	
end

app/models/matriz.rb
class Matriz < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle_category.rb
class VehicleCategory < ActiveRecord::Base
end

app/controllers/adminarea_controller.rb
class AdminareaController < ApplicationController

	before_action :authenticate_admin! 
  def index
  end



end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController

	before_action :find_cidade, only: [:show, :destroy] 
	

	def index
		@cidade = Cidade.all
		@lojas = Loja.all

	end

	def show
		@lojas = Loja.all
	end

	def new
		@cidade = Cidade.new
	end

	def create
		@cidade = Cidade.new(cidade_params)
		if @cidade.save
			redirect_to @cidade
		else
			render 'new' 
		end
	end

	def destroy
		@cidade = Cidade.find(params[:id])
    if @cidade.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end





	private

	def find_cidade
		@cidade = Cidade.find(params[:id])
	end

	def cidade_params
		params.require(:cidade).permit(:name, :estado_id, :loja_id)
	end



end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController

	before_action :find_estado, only: [:show, :edit, :update, :destroy]

#
#  Nao esquecer de ligar.
##############################################################
	before_action :authenticate_admin! , except: [:index, :show]

	def index
		@estados = Estado.all.order("name ASC")
  #  @cidades = Cidade.all
	end

	def show
      @estado = Estado.find(params[:id])
      @cidades = @estado.cidades.order("name ASC")
	end

  def edit
  end

  def new
  	@estado = Estado.new
  end

  def create
  	@estado = Estado.new(estado_params)
  	if @estado.save
  		redirect_to @estado ,notice: "Cadastrado com Sucesso"
  	else
  		render 'new'
  	end
  end

  def update
    if @estado.update(estado_params)
      redirect_to @estado, notice: "Atualizado com Sucesso"
    else
      render 'edit'
    end
  end

  def destroy
    if @estado.destroy
      redirect_to estados_path , notice: "Deletado com Sucesso"
    else
      render 'show'
    end
  end




  private

  def find_estado
  	@estado = Estado.find(params[:id])

  end

  def estado_params
  	params.require(:estado).permit(:name , :cidade_id)
  end






end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController

	before_action :find_loja, only: [:show, :edit, :update, :destroy]


	def index
		@lojas = Loja.all.order("created_at DESC")

	end

	def show
	end

	def edit
	end

	def new
		@loja = Loja.new
	end

	def create
		@loja = Loja.new(loja_params)
		if @loja.save
			redirect_to @loja, notice: "Loja Cadastrada com Sucesso"
		else
			render 'new'
		end
	end

	def update
		if @loja.update(loja_params)
			redirect_to @loja, notice: "Atualizado com Sucesso"
		else
			render 'edit'
		end
	end


	def destroy
		if @loja.destroy
				redirect_to lojas_path, notice: "Loja Deletada com Sucesso"
		end
	end










	private

	def find_loja
		@loja = Loja.find(params[:id])
	end

	def loja_params
		params.require(:loja).permit(:name, :cidade_id, :endereco, :telefone, :email, :owner, :mapa)

	end







end

app/controllers/ultrabooks_controller.rb
class UltrabooksController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


  def sobre
  end

  

  def franquias
  end

  def contato
  end
end

app/helpers/adminarea_helper.rb
module AdminareaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

		def tipo(type)
		case type
		when :success then "success"
		when :error   then "warning"
		when :alert   then "warning"
		when :notice  then " "
		else "info"
		end
	end



	def full_name
			" ( " "#{current_admin.name}"  " ) "
	end



end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/matrizs_helper.rb
module MatrizsHelper
end

app/helpers/ultrabooks_helper.rb
module UltrabooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ultra</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
    <!-- Animate CSS -->
    <link href="css/animate.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">

<div class="container">


	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>

		<a>
		<!-- <%= link_to image_tag( 'logoUltra.png', size: "50x50"), root_path, id: "logo" %> -->
			<%= link_to "Ultra", root_path , class: "navbar-brand" %>
		</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
		</ul>
		<ul class="nav navbar-nav navbar-right">
				<% if admin_signed_in? %>
			<ul class="nav navbar-nav navbar-right">
					<li>	
					<%= link_to current_admin.email + full_name , edit_admin_registration_path %>
					</li>
					<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Cadastros <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
            	<%= link_to 'Estados & Cidades', estados_path %>
            </li>
            <li>
            	<%= link_to 'Lojas', lojas_path %>
            </li>
            <li>
            <%= link_to 'Veículos', vehicle_categories_path %>
            </li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
         
         
	
			<li>    				
					<%= link_to 'Log Out', destroy_admin_session_path,  method: :delete %>
					</li>
		 </ul>


			<% else %>

			<li>
				<%= link_to 'Sobre', :sobre %>
			</li>
			<li>
				<%= link_to 'Lojas', :estados %>
			</li>
			<li>
				<%= link_to 'Franquias', :franquias %>
			</li>
			<li>
			<%= link_to 'Ultrabook', ultrabooks_index_path %>
			</li>
			<li>
				<%= link_to 'Contato', :contato %>
			</li>

		</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->

	<% end %>
</nav>
</div>

<!-- 

<div class="alert">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<strong>
	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
 
	</strong>
</div>  -->


<% flash.each do |name,msg| %>
<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<!-- 

 <% flash.each do |type,message| %>
    <div data-alert class="alert-box success radius<%= tipo type %>">
          <%= message %>
  <a href="#" class="close">&times;</a>
</div>
  <% end %>

 -->
<div class="container">
<!-- 
<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p> -->

<%= yield %>


</div>
</body>
</html>


<!-- 
<div class="container">
<div class="col-md-5 well">
	
	<h2>Sign up</h2>
	<hr>
	<form>
			<fieldset>
	 -->